export const productdata = [
    {
        _id: "1",
        productname: "smartphone",
        productimage: "https://m.media-amazon.com/images/I/818VqDSKpCL._SX569_.jpg",
        brandname: "Samsung",
        description: "Experience the power and speed of the Samsung Galaxy S21. Equipped with the latest Exynos processor, this smartphone delivers seamless performance for all your tasks. Capture stunning photos and videos with its triple camera setup featuring a 108MP main sensor. Enjoy immersive viewing on the Dynamic AMOLED 2X display with a 120Hz refresh rate. With 5G connectivity, stay connected at lightning-fast speeds wherever you go. The sleek design and premium build make the Galaxy S21 a true flagship device.",
        title: "Samsung Galaxy S21 5G (8 GB/128 GB, Phantom Gray)",
        quantity: "30",
        prize: "80000",
    },
    {
        _id: "2",
        productname: "television",
        productimage: "https://m.media-amazon.com/images/I/510uaaRthOL._SY300_SX300_QL70_FMwebp_.jpg",
        brandname: "Sony",
        description: "Transform your entertainment experience with the Sony Bravia X90J 4K HDR TV. Featuring a vibrant TRILUMINOS Pro display and XR Cognitive Processor, this TV delivers lifelike picture quality with stunning clarity and contrast. Enjoy smooth motion and immersive sound with Dolby Vision and Dolby Atmos support. With Google TV built-in, you can easily access all your favorite streaming apps and content. The sleek design and slim bezels elevate the look of any room. Bring the cinema home with the Sony Bravia X90J.",
        title: "Sony Bravia X90J 139 cm (55 inch) 4K Ultra HD LED Google TV KD-55X90J (Black) (2021 Model)",
        quantity: "20",
        prize: "100000",
    },
    {
        _id: "3",
        productname: "headphones",
        productimage: "https://m.media-amazon.com/images/I/312Gw7w4CVL._SX300_SY300_QL70_FMwebp_.jpg",
        brandname: "Bose",
        description: "Immerse yourself in music like never before with the Bose QuietComfort 45 headphones. Featuring world-class noise cancellation technology, these headphones block out distractions so you can focus on your music. Enjoy crisp, clear sound with deep, powerful bass thanks to the premium audio drivers. With up to 24 hours of battery life, you can listen all day without interruption. The lightweight and comfortable design make these headphones perfect for long listening sessions. Elevate your audio experience with the Bose QuietComfort 45.",
        title: "Bose QuietComfort 45 Wireless Noise Cancelling Headphones - Triple Black",
        quantity: "40",
        prize: "35000",
    },
    {
        _id: "4",
        productname: "tablet",
        productimage: "https://m.media-amazon.com/images/I/71RQMHbQTHL._SX679_.jpg",
        brandname: "Microsoft",
        description: "Unleash your creativity with the Microsoft Surface Pro 8. Featuring a stunning PixelSense display and powerful Intel Core processor, this tablet delivers exceptional performance for work and play. With support for the Surface Pen and Surface Dial, you can sketch, write, and design with precision. Stay productive all day with up to 16 hours of battery life and fast charging capability. The versatile design allows you to use the Surface Pro 8 in laptop, studio, or tablet mode. Take your productivity to the next level with the Microsoft Surface Pro 8.",
        title: "Microsoft Surface Pro 8 (11th Gen Intel Core i5, 8GB RAM, 128GB SSD, Windows 11 Home) - Platinum",
        quantity: "15",
        prize: "90000",
    },
    {
        _id: "5",
        productname: "camera",
        productimage: "https://www.tanotis.com/cdn/shop/products/canon_eos_6d_mark_ii_1499359826000_1346735_800x.jpg?v=1576002575",
        brandname: "Canon",
        description: "Capture stunning images and videos with the Canon EOS R5 mirrorless camera. Equipped with a high-resolution sensor and advanced autofocus system, this camera delivers professional-quality results every time. With 8K video recording capability, you can create cinematic masterpieces with unparalleled detail and clarity. The built-in image stabilization ensures steady shots, even in challenging shooting conditions. With its ergonomic design and intuitive controls, the EOS R5 is a joy to use for photographers of all skill levels.",
        title: "Canon EOS R5 Full-Frame Mirrorless Camera (Body Only)",
        quantity: "10",
        prize: "350000",
    },
    {
        _id: "6",
        productname: "smartwatch",
        productimage: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/latitude-notebooks/14-5431/media-gallery/gray/notebooks-latitude-14-5431-gray-gallery-4.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=539&qlt=100,1&resMode=sharp2&size=539,402&chrss=full",
        brandname: "Apple",
        description: "Stay connected and active with the Apple Watch Series 7. Featuring a stunning Retina display and advanced health tracking features, this smartwatch is your ultimate companion for a healthy lifestyle. With the new Always-On display, you can easily check the time and your notifications at a glance. Track your workouts, monitor your heart rate, and stay motivated to reach your fitness goals with the built-in activity tracker. With water resistance up to 50 meters, you can wear the Apple Watch Series 7 everywhere, from the pool to the gym.",
        title: "Apple Watch Series 7 GPS, 41mm Aluminum Case with Sport Band",
        quantity: "50",
        prize: "50000",
    },
    {
        _id: "7",
        productname: "speaker",
        productimage: "https://static.vplak.com/images/sonos/MOVE/black/image-1.jpg",
        brandname: "Sonos",
        description: "Elevate your audio experience with the Sonos One (Gen 2) smart speaker. Featuring rich, room-filling sound and built-in voice control, this speaker is perfect for music lovers and smart home enthusiasts alike. With support for multiple streaming services and seamless integration with other Sonos speakers, you can enjoy your favorite music in every room of your home. The compact and stylish design blends seamlessly into any decor. Bring your music to life with the Sonos One (Gen 2) smart speaker.",
        title: "Sonos One (Gen 2) - Voice Controlled Smart Speaker with Amazon Alexa Built-in - Black",
        quantity: "35",
        prize: "25000",
    },
    {
        _id: "8",
        productname: "gaming console",
        productimage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRG1JZnyzbxoce0GbkL76GbcgGInf5dWkgFlLyIOC7_1uwRFY4J8BvJ-JG2ITzZO-9i9Aw&usqp=CAU",
        brandname: "Sony",
        description: "Experience the next generation of gaming with the Sony PlayStation 5. Featuring lightning-fast load times and stunning 4K graphics, this console delivers immersive gaming experiences like never before. With the new DualSense controller, you can feel every impact and texture in your games for a more realistic experience. Explore a library of exclusive titles and blockbuster hits, from action-packed adventures to epic multiplayer battles. With support for 3D audio and haptic feedback, the PlayStation 5 transports you to new worlds of gaming.",
        title: "Sony PlayStation 5 Console",
        quantity: "5",
        prize: "60000",
    },
    {
        _id: "9",
        productname: "fitness tracker",
        productimage: "https://www.dealsplant.com/cdn/shop/products/fitbit-health-personal-care-fitbit-fb507rgpk-versa-2-health-fitness-smartwatch-with-heart-rate-music-alexa-built-in-s-l-bands-included-petal-copper-rose-15889059774539.jpg?v=1647761617&width=1200",
        brandname: "Fitbit",
        description: "Track your fitness goals and stay motivated with the Fitbit Charge 5. Featuring advanced health and fitness tracking features, this tracker helps you stay on top of your wellness journey. Monitor your heart rate, track your sleep, and measure your activity levels throughout the day. With built-in GPS, you can accurately track your workouts and outdoor activities. The slim and stylish design makes the Fitbit Charge 5 perfect for everyday wear. Stay connected and in control of your health with the Fitbit Charge 5.",
        title: "Fitbit Charge 5 Fitness and Activity Tracker with Built-in GPS, Heart Rate, Sleep & Swim Tracking, Black/Graphite, One Size",
        quantity: "45",
        prize: "15000",
    },
    {
        _id: "10",
        productname: "laptop",
        productimage: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/latitude-notebooks/14-5431/media-gallery/gray/notebooks-latitude-14-5431-gray-gallery-4.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=539&qlt=100,1&resMode=sharp2&size=539,402&chrss=full",
        brandname: "Dell",
        description: "Power through your workday with the Dell XPS 15 laptop. Featuring a stunning InfinityEdge display and powerful Intel Core processor, this laptop delivers uncompromising performance for all your tasks. With up to 32GB of RAM and a spacious SSD, you can multitask with ease and store all your files and documents. The sleek and portable design makes the XPS 15 perfect for professionals on the go. Stay productive and connected with the Dell XPS 15.",
        title: "Dell XPS 15 9500 15.6 inch UHD+ Touchscreen Laptop (Silver) Intel Core i7-10750H 10th Gen, 16GB DDR4 RAM, 1TB SSD, Nvidia GTX 1650 Ti with 4GB GDDR6, Windows 10 Home",
        quantity: "20",
        prize: "200000",
    }
]
